### ISSUE TITLE
does not work with setting.json

### ISSUE THREAD

**Issue by azriel1rf** [TheButlah/vscode-reorder-python-imports#14]
I added the following setting to the `settings.json`.
```json
    "reorder-python-imports.args": [
        "--py310-plus",
        "--add-import 'from __future__ import annotations'",
    ],
```
![image](https://user-images.githubusercontent.com/43790845/156542372-d307e942-3e8b-4a67-a71a-53ea576dc12d.png)
Those lines are highlighted and the message says `Unknown Configuration Setting`.

The setting does not work.

**Comment by azriel1rf** [comment]
I found that the implementation of the configuration is newer than `v0.1.0` the latest version on the market place.
Publish it to market place, please. @TheButlah

**Comment by azriel1rf** [comment]
Or would you mind if add @tetov to the maintainer?

**Comment by TheButlah** [comment]
Yes, I would be happy to add a maintainer! @azriel1rf just lmk who

**Comment by tetov** [comment]
I wouldn't mind. Would I need some kind of extra access to update the extension in the gallery?

**Comment by TheButlah** [comment]
Most likely, yes - I've added you as a collaborator and can promote to maintainer when you accept the invite. If you want, you could look into getting an auto-deploy workflow running, if not I can look at this when I have time this weekend.

I'm not really around actively maintaining this, so an auto-deploy workflow would be the best approach I think. Just not sure how to keep my personal private key private :)

**Comment by tetov** [comment]
> If you want, you could look into getting an auto-deploy workflow running, if not I can look at this when I have time this weekend.

I enjoy ci-setup quite a lot. I'll look into it. 
> 
> I'm not really around actively maintaining this, so an auto-deploy workflow would be the best approach I think. Just not sure how to keep my personal private key private :)

You add your key as an environment secret in the repo that is referenced in the github workflow. Or even better you add a key specific to this repo as a secret. :)

**Comment by TheButlah** [comment]
Let me know if any permissions need to be granted on your end or any keys/secrets need to be generated for the vscode extension library.

I see a bunch of merged PRs that I didn't before - were those always there lol? Or did your fork and mine somehow combine along with the PR issues?

**Comment by tetov** [comment]
Don't worry about it.

I'll merge my PR eventually but first focus on auto-deploy :).

**Comment by tetov** [comment]
@TheButlah Could you please look over the branch protection settings please? Currently PR's can only be `rebase and merged` which is fine but the commits needs to be signed which github web UI can't do: 
![image](https://user-images.githubusercontent.com/14882117/158701125-745d7191-81ff-4c63-98da-a5653c01899a.png)
 
I can rebase merge (with gpg signatures) from command line but that will get tedious for dependabot alerts..

**Comment by tetov** [comment]
Also, I've merged my PR's except the one which extends the test suite and runs it in CI.

If there is a good mechanism for releasing a preview version of an extension I'd love to do that. I don't want to release current master before more test, either automated or manual.

**Comment by TheButlah** [comment]
>  Currently PR's can only be `rebase and merged` which is fine but the commits needs to be signed which github web UI can't do

Updated branch protection rules to not require signed commits. Would like to leave the rebase and merge requirement though if thats not going to cause too much trouble

**Comment by TheButlah** [comment]
> If there is a good mechanism for releasing a preview version of an extension I'd love to do that. I don't want to release current master before more test, either automated or manual.

There is a preview flag in the manifest, but I think that would mark the extension as a whole as a preview, instead of making it a beta like you seem to intend to. Honestly marking it as a preview and making it a beta via SemVer is probably the right way.

https://code.visualstudio.com/api/references/extension-manifest

**Comment by tetov** [comment]
Leaving an update here too:

This issue can be solved in two ways. Either by @TheButlah releasing a pre-release (you can provide normal and pre-release versions from the same plugin now) as described in the readme in #25. Or by doing a "normal" release which anyone with access to push tags to this repo can do (so currently me or @TheButlah) after #25 is closed and access key added to repo.

**Comment by tetov** [comment]
@azriel1rf I've released v0.2.0 now which includes the settings key. Please try it out :). Please reopen if this issue or create another if you have any problems with 0.2.0.

**Comment by jahamilton12121** [comment]
This does not seem to work for me. I am adding this to my settings.json
```
"[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": false,
            "source.organizeImports.reorder-python-imports": true
        },
    }
```
Saving does not reorder imports

**Comment by TheButlah** [comment]
@jahamilton12121 what version of the extension are you using?

**Comment by jahamilton12121** [comment]
0.2.0

**Comment by jahamilton12121** [comment]
So re-order imports does not work at all actually, only sort imports does
