### ISSUE TITLE
Extension on Windows is adding additional new line for every import line

### ISSUE THREAD

**Issue by piotrgredowski** [TheButlah/vscode-reorder-python-imports#155]
Happening when:
- saving and having reordering enabled on save.
- right clicking and selecting `Reorder imports`.
![reorder_issue](https://user-images.githubusercontent.com/4294480/220560779-fb300a33-bb38-4798-bbab-05a829b26313.gif)

When running `pre-commit run reorder-python-imports` from command or PS - problem is not occurring.
If there will be no volunteer to look into that issue - I'll try to find some time and fix it.

VSCode info:
```
Version: 1.67.2 (system setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z (9 mos ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by TheButlah** [comment]
I don't actively maintain this project rn, so a PR would be appreciated
