### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by tetov** [TheButlah/vscode-reorder-python-imports#27]
For Eclipse Theia (GitPod & more) and VS Codium.

Open VSX [Motivation](https://www.gitpod.io/blog/open-vsx/)
[Open VSX publishing instructions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

@TheButlah Could you set up an account, namespace and access key there as well?

**Comment by TheButlah** [comment]
Do we really need to do this? I would expect users using forks of vscode to be capable of downloading a vsix from our releases and using that directly

**Comment by tetov** [comment]
Fair enough.
