### ISSUE TITLE
Pass `--application-directories`

### ISSUE THREAD

**Issue by paw-lu** [TheButlah/vscode-reorder-python-imports#4]
As a cli, I usually run

```sh
reorder-python-imports --application-directories=src
```

when the project uses an `src/` directory.

Is there a way to pass a value to the `--application-directories` arg through the extension?

---

Thanks for the extension, it's been really useful!

**Comment by tetov** [comment]
@paw-lu There is now after #5, through a general `args` parameter.

Would it be of interest to add more parameters? Like having a configuration value named 
`"Application directories": {value}` where which is passed like this: `reorder-python-imports --application-directories={value}`?

Having a general `args` conf makes the vscode plugin easier to maintain, but maybe it's worth it?

**Comment by paw-lu** [comment]
> @paw-lu There is now after #5, through a general args parameter.

Awesome. Thank you so much! This is really appreciated.

> Would it be of interest to add more parameters?

Hard call. I think the general `args`—like you said—is a general solution that is flexible and more future proof. Plus it's in line with what VSCode does for other Python linting tools.

```json
{
    "python.linting.flake8Args": [],
    "python.linting.black8Args": [],
    "python.testing.pytestArgs": []
}
```

Having individual config settings would definitley be nice—as you can directly point out the options to the user and use hints for the valid parameters—but might not be worth the upkeep costs to keep it in sync with the main tool. In addition you'll add some additional complexity as `args` can conflict with the individual parameter values.

**Comment by tetov** [comment]
After some more thinking I remembered [this comment from @asotille](https://github.com/asottile/reorder_python_imports/issues/101#issuecomment-537936957). It isn't technically applicable here because vscode handles the settings API for us but the sentiment resonates with me. `args` is enough, as long as the extension can run the command correctly everything is fine.

**Comment by paw-lu** [comment]
Going to close this issue as @tetov addressed the core issue.
